Support Independent Vertical and Horizontal Scaling for Planes API
linux4sam/libplanes pull request #1
Opened 2019-10-18 19:41 UTC by ksloataamp

libplanes: Add ability to implement independent vertical and horizontal scaling.

Currently, the API to libplanes allows only setting a uniform scale factor that
will equally scale both width and height. At the lower kms level, the function
actually does set the width and height, so this patch simply exposes this
to the planes level to allow individual scaling. Note that this does not
add parameters for the JSON/config interface but these can be added in the
future if desired.

2019-10-21 23:28 UTC, joshua-henderson requested changes
Thank you for the patch.  This is a nice change.  Outside of the couple things to fix I noted, if you could please add a Signed-off-by: (see [Developer Certificate of Origin](https://developercertificate.org/)) line to your single commit message it would be very appreciated and we'll get this applied.

2019-10-21 23:28 UTC, joshua-henderson commented on include/planes/plane.h
> +void plane_set_scale(struct plane_data* plane, double scale_x, double scale_y);
This is a breaking API change.  Instead, leave the original definition there and add a new one that looks something like this.

`void plane_set_scale_independent(struct plane_data* plane, double scale_x, double scale_y);`

Then make the original plane_set_scale() call your new function with the same value for both parameters.  I'm not incredibly worried about the change in struct plane_data.  I'll add the proper missing getter functions with this change for scale in both dimensions.

2019-10-21 23:28 UTC, joshua-henderson commented on include/planes/plane.h
> + * @param scale_y Vertical scale of the plane, where 1.0 is no scale.
Change is fine.  No need to make this a separate commit.  This is all good in one single commit.

2019-10-22 11:29 UTC, ksloataamp commented
> nice change. Outside of th

Sounds good @joshua-henderson I will make the changes and then resubmit a new pull request, thanks.

2019-10-22 11:29 UTC, closed without merging